### ISSUE TITLE
Apply to a round

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#115]
**User Story**
As a project owner, 
I want to fill out and submit an application 
so that I can apply for a round 

**Acceptance Criteria:**
[TBD] 

**Tasks**
- [ ] Select and import existing project - 2
- [ ] Create form + Request from round manager what inputs/questions to render - 4
- [ ] Submit an application on-chain + Write to round contract - 4 
- [ ] for collected PII (i.e. if round operator asks for email), we need to encrypt the data and send it to RM and understanding how RM can decrypt this information - TBD, after conversation 
- [ ] View your project details dropdown - 2

**Open Question**
* Eng - would you recommend "autofilling" the application or just sending the full project every time? (may need to update designs if autofill) 
>> Let's assume we are sending the full project with each application. 
* How do we encrypt? 
>> From RM side, they should let us know what fields need to be encrypted or not. Will also need a public key 

**Link to mocks:** https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=1313%3A2598

<img width="708" alt="Screen Shot 2022-06-29 at 9 33 47 PM" src="https://user-images.githubusercontent.com/26017180/176577020-13c53203-0ea2-4a94-9ed1-d44265c842b3.png">

Context from Aditya on Round Manager encryption: 
![Image](https://user-images.githubusercontent.com/26017180/176696113-2e541c28-7837-47f4-9e19-23739e9020c1.png)
