### ISSUE TITLE
Preview Application 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#141]
**Tasks** 
- [ ] "View your project details dropdown" - Display selected project's details in view-only state 
- [ ] Display application answers in view-only state 
- [ ] "Back to Editing" button 

Link to mocks: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=1313%3A2598

<img width="706" alt="Screen Shot 2022-07-11 at 9 19 54 AM" src="https://user-images.githubusercontent.com/26017180/178273658-06fb1c63-cefd-4f3c-8c23-02e43b0d6f0e.png">
<img width="705" alt="Screen Shot 2022-07-11 at 9 20 26 AM" src="https://user-images.githubusercontent.com/26017180/178273670-705f00d3-b438-4c22-8989-03fce94cbd93.png">
<img width="702" alt="Screen Shot 2022-07-11 at 9 20 37 AM" src="https://user-images.githubusercontent.com/26017180/178273677-dbe8ffbd-c7de-4ae3-9f8b-b96922b5fc58.png">

**Comment by schultztimothy** [comment]
@michellema1208 
A couple thoughts while building out the form. 

1. If we are to display placeholder text in inputs it will have to come from the RM
2. Validation will be somewhat limited. There is a required field on the application field, but beyond that it may be hard to determine what to validate
