### ISSUE TITLE
Make updates to image fields (logo, banner) in the project form

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#164]
**Tasks**: 

- [ ] Add banner image field (image validation: 1,500 x 500. Same as Twitter) 
- [ ] Validate image size for logo depending on needs of Optimism FE Grant Explorer (TBD - coming soon) 
- [ ] Add black background by default like cGrants

**Comment by schultztimothy** [comment]
@michellema1208 @willsputra I updated the `Recommended` messaging to `Required` since its required now. Just wanted to note that here since it doesn't match the designs. 

![Image](https://user-images.githubusercontent.com/6887938/180060317-75373cb5-bac8-425c-856d-0358c0f24c73.png)
