### ISSUE TITLE
[DESIGN] Project verification UX work

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#182]
**Tasks**

- [ ] Project verification CTAs on the project creation form -- two options, one with input text field and one with just CTA (note: input text field version may have eng implications on edit flow bc when you change your username, your verification needs to be stripped) 
- [ ] Project verification CTAs on the edit form 

**Bonus** 

- [ ] Error state? 
- [ ] Messaging to users who choose to verify after a project has been created
- [ ] Project Details verification CTA
