### ISSUE TITLE
project profile: design spec updates 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#368]
**Tasks**
- [ ] Project Profile: Make the Project Details font smaller ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![projectdetailsbutton](https://user-images.githubusercontent.com/26017180/191626703-18684442-5a58-4f5b-b816-58461ef158f5.png)

- [ ] Project Profile: Header image should be full width, keep the aspect ratio ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![header](https://user-images.githubusercontent.com/26017180/191626712-895ab936-a29e-4d52-aae3-f4dec495f622.png)

- [ ] Project Profile: The font style and sizes for paragraph text and link seem to be different ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![detailsparagraph](https://user-images.githubusercontent.com/26017180/191626719-7aaa44e2-4775-4943-b6a4-aca311ae87e4.png)

**Comment by michellema1208** [comment]
@willsputra can the engineers find the exact specs from the Figma file itself?

**Comment by willsputra** [comment]
yep! we're following the tailwind font sizes (https://tailwindcss.com/docs/font-size)

<img width="836" alt="image" src="https://user-images.githubusercontent.com/19514207/191754844-c93b09b7-0bde-41e2-905c-5e35dca190ca.png">

you can also go to the Inspect tab to see the details

<img width="859" alt="image" src="https://user-images.githubusercontent.com/19514207/191755161-bc3216e2-73d2-44ad-89dd-97b9322dd954.png">
